name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Add Nuget Source
      run:  dotnet nuget add source https://nuget.pkg.github.com/Warhammer4000/index.json -n github -u Warhammer4000 -p ${{ secrets.TOKEN_GITHUB }}
    - name: Build
      run: dotnet pack --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish GitHub
      run: dotnet nuget push "bin/Release/*.nupkg" --source "github"
    - name: Publish Nuget
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: DTD.Sort.Net.Main/DTD.Sort.Net.Main.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
       
